# Auth Service Configuration
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# User Service Configuration
user-service:
  url: http://localhost:8082
  timeout: 5000
